name: Context Dump
run-name: ${{ github.actor }} is dumping ALL Context - re
on: [push]
jobs:
    dump-contexts-to-log:
        runs-on: ubuntu-latest
        steps:
            - name: Dump GitHub Context
              run: echo "$GITHUB_CONTEXT"
              env:
                GITHUB_CONTEXT: ${{ toJson(github) }}
            
            - name: Dump Job Context
              run: echo "$JOB_CONTEXT"
              env:
                JOB_CONTEXT: ${{ toJson(job) }}
            
            - name: Dump Steps Context
              run: echo "$STEPS_CONTEXT"
              env:
                STEPS_CONTEXT: ${{ toJson(steps) }}
            
            - name: Dump Runner Context
              run: echo "$RUNNER_CONTEXT"
              env:
                RUNNER_CONTEXT: ${{ toJson(runner) }}
        