name: Script Runner
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
    run-first-script-action:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: Make script files executable
              run: chmod +x first-script.sh second-script.sh
            - name: Run scripts
              run: |
                first-script.sh
                second-script.sh